import styles from "@styles/Home.module.css";
import RootLayout from "@templates/RootLayout/RootLayout";

import IntroTitle from "@organisms/IntroTitle/IntroTitle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <RootLayout>
          <IntroTitle>
            <IntroTitle.Title>LUKE BRANNAGAN</IntroTitle.Title>
            <IntroTitle.Subtitle>FRONTEND DEVELOPER</IntroTitle.Subtitle>
          </IntroTitle>
        </RootLayout>
      </main>
    </>
  );
}
