import AnimateIntoView from "@animations/AnimateIntoView/AnimateIntoView";
import RandomGlow from "@animations/RandomGlow/RandomGlow";
import About from "@organisms/About/About";
import IntroTitle from "@organisms/IntroTitle/IntroTitle";
import RootLayout from "@templates/RootLayout/RootLayout";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RootLayout>
          <IntroTitle>
            <IntroTitle.Title>
              <AnimateIntoView>
                LUKE <br /> BRANNAGAN
              </AnimateIntoView>
            </IntroTitle.Title>
            <AnimateIntoView once={false} inViewVariant={{ y: 30 }}>
              <IntroTitle.Subtitle>FRONTEND DEVELOPER</IntroTitle.Subtitle>
            </AnimateIntoView>
            <IntroTitle.Video src="/videos/splash4.mp4" autoPlay muted loop />
          </IntroTitle>
          <AnimateIntoView once={false}>
            <About>
              <About.Image src="/img/profile.jpeg" />
              <About.Content>
                My name is Luke, and I am a{" "}
                <RandomGlow>front-end developer </RandomGlow> with{" "}
                <RandomGlow>4 years </RandomGlow> of experience. I specialise in
                building <RandomGlow>modern, responsive websites </RandomGlow>{" "}
                and web applications.
                <br />
                <br />I am passionate about creating{" "}
                <RandomGlow>intuitive and engaging user experiences</RandomGlow>
                , and I believe that{" "}
                <RandomGlow>clean, well-designed code </RandomGlow> is the key
                to achieving this. I am constantly learning and staying
                up-to-date with the latest technologies and{" "}
                <RandomGlow>best practices </RandomGlow> in the industry.
              </About.Content>
            </About>
          </AnimateIntoView>
        </RootLayout>
      </main>
    </>
  );
}
